### ISSUE TITLE
Update TravisCI to support QA testing and deployment in addition to Release

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/jthegedus.github.io#30]
- [x] run builds/tests on PR and commits to PRs
- [x] deploy to STAG server (surge) ONLY on success of merge to STAG BRANCH - from DEV branch PR.
- [x] deploy to PROD server (github master branch) ONLY on success of merge to  PROD BRANCH - from STAG branch PR.

**Comment by jthegedus** [comment]
Create scripts or use the inline-bash commands in the .travis.yml file?

**Comment by jthegedus** [comment]
Create scripts (Y)

**Comment by jthegedus** [comment]
An inaccurate but possible Travis YAML file
```yaml
language: node_js
branches:
  only:
    - stag
    - prod
before_install:
  - openssl aes-256-cbc -K $encrypted_8e369f2dc660_key -iv $encrypted_8e369f2dc660_iv -in id_rsa.enc -out id_rsa -d
script:
  - yarn run format
  - yarn run lint
  - yarn run proof
  - yarn run test
after_success:
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "This will deploy!"
    echo "Building..."
    yarn run build
    if [ "$TRAVIS_BRANCH" == "develop" ]
      echo "Deploying to STAG (surge)"
      yarn run deploy_stag_serv
    else
      echo "Deploying to PROD (GitHub Master branch)"
      yarn run deploy_prod_serv
  else
    echo "This will not deploy!"
  fi

env:
  global:
    - DEPLOY_BRANCH="release"
    - SOURCE_DIR="public"
    - TARGET_BRANCH="master"
    - SSH_KEY="id_rsa"
    - GIT_NAME="jthegedus"
    - GIT_EMAIL="jthegedus@jttech.io"
```

**Comment by jthegedus** [comment]
The following successfully runs PR builds and subsequent commits to PRs
```yaml
language: node_js
branches:
  only:
    - dev
    - stag
    - prod
```

**Comment by jthegedus** [comment]
Ended up using the deploy methods built in to TravisCI

```yaml
deploy:
  # Deploy to staging server (surge.sh)
  - provider: script
    script: yarn run deploy_stag
    skip_cleanup: true
    on:
      branch: stag
  # Deploy to production server (GitHub Master branch)
  - provider: script
    script: yarn run deploy_prod
    skip_cleanup: true
    on:
      branch: prod
```
